/******** QUESTION 1  ********/
create table PATIENT
(
PATIENT_ID		NUMBER PRIMARY KEY NOT NULL,
LAST_NAME		VARCHAR2(30) NOT NULL,
FIRST_NAME		VARCHAR2(25) NOT NULL,
DOB				DATE,
INS_CODE		NUMBER
);
INSERT INTO PATIENT VALUES (1, 'KUMAR', 'RAMESH', '05/10/2000', 24)
CREATE TABLE PHYSICIAN 
(
PHYSICIAN_ID	NUMBER PRIMARY KEY NOT NULL,
LAST_NAME		VARCHAR2(30) NOT NULL,
FIRST_NAME		VARCHAR2(25) NOT NULL,
LICENSE_NO		NUMBER(7) NOT NULL,
HIRE_DATE		DATE
);


CREATE TABLE ROOM
(
ROOM_ID			NUMBER PRIMARY KEY NOT NULL,
FLOOR_NO		NUMBER
);

CREATE TABLE ADMISSION
(
ADMISSION_ID	NUMBER PRIMARY KEY NOT NULL,
PATIENT_ID		NUMBER REFERENCES PATIENT(PATIENT_ID) NOT NULL,
PHYSICIAN_ID	NUMBER REFERENCES PHYSICIAN(PHYSICIAN_ID) NOT NULL,
ADMIT_DATE		DATE,
DISCHG_DATE		DATE,
ROOM_ID			NUMBER REFERENCES ROOM(ROOM_ID)
);


/******** QUESTION 2  ********/

--Add ‘mobile_no’ coumn to the ‘PATIENT’ table and make it as Unique key.

ALTER TABLE PATIENT
ADD MOBILE_NO NUMBER UNIQUE;

--Update mobile number for all the patient

UPDATE PATIENT SET MOBILE_NO = 9373922064 WHERE PATIENT_ID = 1;

COMMIT;

UPDATE PATIENT SET MOBILE_NO = 9373922058 WHERE PATIENT_ID = 2;

COMMIT;

--Add ‘Qualification’ column to the ‘PHYSICIAN’ table and make it as not null column.

ALTER TABLE PHYSICIAN
ADD QUALIFICATION VARCHAR2(20) NOT NULL;

--Update Qualification for all physicians.

UPDATE PHYSICIAN SET QUALIFICATION = 'B.Sc.,' WHERE PHYSICIAN_ID = 1;
COMMIT;
UPDATE PHYSICIAN SET QUALIFICATION = 'M.Sc.,' WHERE PHYSICIAN_ID = 2;
COMMIT;

--Drop ‘Last_name’ column from the physician table.

ALTER TABLE PHYSICIAN
DROP LAST_NAME;

--Delete the patient only who has born after the year of 2000 from the patient table.

DELETE FROM PATIENT
WHERE DOB >  TO_DATE( '12/31/2000', 'MM/DD/YYYY');

COMMIT;

--Rename ‘DOB’ column to ‘Date_Of_Birth’ on both tables.

ALTER TABLE PATIENT
RENAME COLUMN DOB TO  DATE_OF_BIRTH;

COMMIT;

--Create backup table ‘PATIENT_BKP’ With Data.
CREATE TABLE PATIENT_BKP AS (SELECT * FROM PATIENT);

----Create backup table ‘PATIENT_BKP1’ Without Data.
CREATE TABLE PATIENT_BKP1 AS 
(SELECT patient_id, last_name, first_name, date_of_birth, ins_code, mobile_no 
FROM PATIENT 
where 1=0);

--Rename ‘ADMISSION’ table to ‘PATIENT_ADMISSION’

RENAME ADMISSION TO PATIENT_ADMISSION;
